import type { NextPage } from "next";
import { readdirSync, readFileSync } from "fs";
import matter from "gray-matter";
import Head from "next/head";
import Link from "next/link";

interface Post {
  title: string;
  date: string;
  category: string;
  slug: string;
}

const Home: NextPage<{ posts: Post[] }> = ({ posts }) => {
  return (
    <div className="w-full flex justify-center">
      <Head>
        <title>프리온보딩 10월</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul className="divide-y-2 w-1/2">
        {posts?.map((item, idx) => (
          <li
            key={idx}
            className="mx-10 mb-5 mt-2 px-10 pt-5 flex items-center justify-between"
          >
            <Link href={`/${item.slug}`}>
              <a className="flex-1 w-full text-center">
                <span className="text-xl font-semibold text-red-500">
                  {item.title}
                </span>
              </a>
            </Link>
            <div>
              <span>
                {item.date} / {item.category}
              </span>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const noticePosts = readdirSync("./__posts").map((file) => {
    const content = readFileSync(`./__posts/${file}`, "utf-8");
    const [slug, _] = file.split(".");
    return { ...matter(content).data, slug };
  });
  return {
    props: { posts: noticePosts.reverse() },
  };
}
